// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4662.KnightByte;

import org.usfirst.frc4662.KnightByte.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

import org.usfirst.frc4662.KnightByte.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    //Buttons
    public JoystickButton loadButton;
    public JoystickButton unloadButton;
    public JoystickButton shooterTrigger;
    public Joystick operatorJoystick;
    public Joystick joystick1;
    public Joystick joystick2;
    public JoystickButton cameraButton;
    public JoystickButton targetToggle;
    public JoystickButton targetShoot;
    public JoystickButton shooterRampUp;
    public JoystickButton shooterPark;
    public JoystickButton shooterStop;
    

    public OI() {
 // BEGIN CONSTRUCTORS

        joystick2 = new Joystick(1);
        joystick1 = new Joystick(0);
        operatorJoystick = new Joystick(2);
        
        targetShoot = new JoystickButton(operatorJoystick, 1);
        targetShoot.whenPressed(new LocateTarget());
        shooterTrigger = new JoystickButton(operatorJoystick, 2);
        shooterTrigger.whileHeld(new Shoot());
        shooterStop = new JoystickButton(operatorJoystick, 2);
        shooterStop.whenReleased(new ShootStop());
//        shooterTrigger.whenReleased(new ShootStop());
        shooterRampUp = new JoystickButton(operatorJoystick, 6);
        shooterRampUp.whenPressed(new ShooterUpDownNoCam());
        shooterPark = new JoystickButton (operatorJoystick, 7);
        shooterPark.whenPressed(new ShooterPark());
        loadButton = new JoystickButton(operatorJoystick, 3);
        loadButton.whileHeld(new LoaderWheels(0.8));
        loadButton.whenReleased(new LoaderWheelStop());
        unloadButton = new JoystickButton(operatorJoystick, 5);
        unloadButton.whileHeld(new LoaderWheels(-0.8));
        unloadButton.whenReleased(new LoaderWheelStop());
        cameraButton = new JoystickButton(operatorJoystick, 11);
        cameraButton.whenPressed(new CameraToggle());
        targetToggle = new JoystickButton(operatorJoystick, 10);
        targetToggle.whenPressed(new TargetToggle());

        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Shoot", new Shoot());
        SmartDashboard.putData("LocateTarget", new LocateTarget());
        SmartDashboard.putData("ShooterUpDown", new ShooterUpDown());
        SmartDashboard.putData("ShooterPark", new ShooterPark());
        SmartDashboard.putData("ShootingCommandGroup", new ShootingCommandGroup());
        SmartDashboard.putData("Rotate Chassis", new RotateChassis(10));
        SmartDashboard.putData("Shooter Move to Top", new ShooterUpDown());
        

 
    }
 // END CONSTRUCTORS
 // BEGIN FUNCTIONS
    public Joystick getOperatorJoystick() {
        return operatorJoystick;
    }

    public Joystick getJoystick1() {
        return joystick1;
    }

    public Joystick getJoystick2() {
        return joystick2;
    }


 // END FUNCTIONS
}

