// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4662.KnightByte.commands;

import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc4662.KnightByte.Robot;
import org.usfirst.frc4662.KnightByte.RobotMap;

import edu.wpi.first.wpilibj.command.Command;
/**
 *
 */
public class RotateChassis extends Command {
	double m_dTargetAngle;
	double m_dOffsetAngle = 0;
	double m_RotateSpeed;
	AnalogGyro gyro = RobotMap.rotationalGyro;
	boolean m_haveAngle = false;
	
    public RotateChassis(double dOffsetAngle) {
    	m_dOffsetAngle = dOffsetAngle;
        requires(Robot.driveSubsystem);
        m_haveAngle = true;
    }
    
    public RotateChassis() {
        requires(Robot.driveSubsystem);
    }
    
    protected void initialize() {
    	if (m_haveAngle == false){
    		m_dOffsetAngle = Robot.shooterCam.GetAngle();
    	}
    	m_dTargetAngle = gyro.getAngle() + m_dOffsetAngle;
    	SmartDashboard.putNumber("Gyro Angle Init", gyro.getAngle());
    	//Have to add the target offset from the camera targeting to the gyro reading, not sure how to pass the value into the command
    	if (m_dOffsetAngle < 0) {
    		m_RotateSpeed = .5;
    	} else if (m_dOffsetAngle > 0){
    		m_RotateSpeed = -.5;
    	} else {
    		m_RotateSpeed = 0;
    	}
    }

    protected void execute() {
    	Robot.driveSubsystem.driveArcadeAutonomous(0,m_RotateSpeed);
    	 SmartDashboard.putNumber("Gyro Angle Execute", gyro.getAngle());
    }

    protected boolean isFinished() {
        boolean bReturnValue = false;
        double currentAngle = gyro.getAngle();
        if (m_dOffsetAngle < 0 && currentAngle <= m_dTargetAngle) {
        	bReturnValue = true;
        } else if (m_dOffsetAngle > 0 && currentAngle >= m_dTargetAngle) {
        	bReturnValue = true;
        } else if (m_dOffsetAngle == 0) {
        	bReturnValue = true;
        }
        return bReturnValue;
    }

    protected void end() {
    	Robot.driveSubsystem.driveArcadeAutonomous(0, 0);
    }

    protected void interrupted() {
    	end();
    }
}
